### ISSUE TITLE
OSX Build?

### ISSUE THREAD

**Issue by gtamas** [aspose-slides/Aspose.Slides-for-C#1]
Can I build or use this library on MaxOSX Catalina?

I mean, Mono and NuGet are available for OSX, but I'm not sure if the  Aspose shared libraray (the .so) would work under OSX.

I tried something like this:

`g++ -shared -o pptparser.so main.o -lphpcpp -lAspose.Slides_clang3_libstdcpp -laspose_cpp_clang3_libstdcpp -L/path/to/aspose-slides-cpp-linux-20.10/lib `

... but the linker says:

ld: warning: ignoring file /path/to/aspose-slides-cpp-linux-20.10/lib/libAspose.Slides_clang3_libstdcpp.so, building for macOS-x86_64...

So this means the shared lib was built for a different architecture and it won't work, right?

Is there any way to use this on Mac or should I go for Ubuntu?

**Comment by gtamas** [comment]
Btw, I'm not a C++ guy, I'm just exploring the possibilities of building a PHP extension to process PPTX files (using Aspose.slides). Should that even be possible?

**Comment by nikolaysaulyak** [comment]
Please use the [Free Support Forum](https://forum.aspose.com/c/slides/11) to ask any questions you may have.
